name: CI

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - run: npm ci --legacy-peer-deps
      - run: npm run build

      - name: Deploy dist directory
        env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY || '' }}
          SSH_CMD_ARGS: '-o StrictHostKeyChecking=no'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -rlgoDzv --delete -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no" dist/ root@${{ secrets.SSH_IP_ADDRESS }}:/var/www/kotibai/frontend
