name: CI

on:
  push:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - run: npm ci --legacy-peer-deps
      - run: npm run build

      - name: rsync deployments
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_PORT: 22
          ARGS: '-rlgoDzvc -i'
          SSH_CMD_ARGS: '-o StrictHostKeyChecking=no'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_IP_ADDRESS }}
          REMOTE_USER: root
          TARGET: /var/www/kotibai/frontend
        run: rsync -rlgoDzv --delete dist/ root@${{ secrets.SSH_IP_ADDRESS }}:/var/www/kotibai/frontend
